language: ruby
rvm:
  - 2.3.0

services:
  - postgresql

before_script:
  - psql -c 'create database romanian_dic_api_test;' -U postgres
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec
