default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: romanian_dic_api_development

test:
  <<: *default
  database: romanian_dic_api_test<%= ENV['TEST_ENV_NUMBER'] %>
